export default {
  initialized: false,
  isLoading: true,
  config: {},
  title: "",
  breadcrumbs: [],
  user: {},
  roles: [],
  entries: [],
  entriesByTag: {},
  tags: [],
  adminPaneIsOpen: false,
  entryFormIsOpen: false,
  api: {},
  token: "",
  editMode: {},
  toasts: [],
  comments: {},
  entryComments: {},
  selectedComments: [],
  settings: {},
  tokens: [],
  drafts: []
};
